import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MusicaeGeneratedModule, MusicaeGeneratedSharedModule } from './generated/module.js';
import { MusicaeValidator, registerValidationChecks } from './musicae-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MusicaeAddedServices = {
    validation: {
        MusicaeValidator: MusicaeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MusicaeServices = LangiumServices & MusicaeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MusicaeModule: Module<MusicaeServices, PartialLangiumServices & MusicaeAddedServices> = {
    validation: {
        MusicaeValidator: () => new MusicaeValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMusicaeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Musicae: MusicaeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MusicaeGeneratedSharedModule
    );
    const Musicae = inject(
        createDefaultModule({ shared }),
        MusicaeGeneratedModule,
        MusicaeModule
    );
    shared.ServiceRegistry.register(Musicae);
    registerValidationChecks(Musicae);
    return { shared, Musicae };
}
